language: python
python: "3.6"
cache: pip

stages:
  - name: test
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: test
      install:
        - pip install --upgrade pip
        - pip install poetry
        - poetry config http-basic.pypi $PYPI_USER $PYPI_PASS
      script:
        - poetry install
    - stage: deploy
      install:
        - pip install --upgrade pip
        - pip install poetry
        - poetry config http-basic.pypi $PYPI_USER $PYPI_PASS
      script:
        - poetry build
        - poetry publish
