language: python
python: "3.6"
cache: pip

stages:
  - name: test
  - name: deploy
    if: tag IS present

env:
  matrix:
  - DJANGO=111
  - DJANGO=20
  - DJANGO=master

matrix:
  fast_finish: true
  allow_failures:
  - env: DJANGO=master

before_install:
  - pip install --upgrade pip
  - pip install poetry
  - poetry config http-basic.pypi $PYPI_USER $PYPI_PASS

jobs:
  include:
  - stage: test
    install: skip
    script:
      - poetry install
  - stage: deploy
    install: skip
    script:
      - poetry build
      - poetry publish
